// <auto-generated />
namespace GoGoNihon_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changekey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changekey));
        
        string IMigrationMetadata.Id
        {
            get { return "201511180541120_changekey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
